# Generated by Django 5.2.6 on 2025-09-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='heroes/')),
            ],
        ),
    ]
