# Generated by Django 5.2.6 on 2025-09-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpost',
            name='post_type',
            field=models.CharField(choices=[('receiver', 'Receiver'), ('donor', 'Donor')], default='receiver', max_length=10),
        ),
    ]
