# Generated by Django 5.2.6 on 2025-09-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_alter_requestpost_post_type_donationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
